version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    vendor: true
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
